#ifndef CONFIG_H
#define CONFIG_H

// Advent of Code version 1.0.2025.1
// Autogenerated header file, do not modify!!
// Header file: config.h
// Last modified: 2025-11-20 11:27:37

namespace AoC
{
    namespace Metadata
    {
        static const char* version = "1.0.2025.1";
        static const char* author = "Marco Carosio";
        static const char* desc = "Advent of Code C++ repo";
        static const char* last_commit_date = "2025-11-20 11:19:45 +0100";
        static const char* last_commit_hash = "4d7898e74ddc00e3c6294be1cc87b770cbc2c127";
    }

    namespace Settings
    {
        static const char *input_directory = "/home/marco/repos/github/mcarosio80/AoC/input";
    }
} // AoC

#endif // CONFIG_H
